#!/usr/bin/env node

var orange_slice = require('./src/slicer.js');

// The url is the 1st argument passed into the script
const url = process.argv[2];

// User didn't specify url
if (!url) {
    console.log("Usage: slice <url>");
    process.exit();
}

// These are example words we want to target
orange_slice.set_danger_words(['links', 'foobar', 'chairs', 'Dinner']);

// Now run the logic on the url given
orange_slice.process_url(url);
